#!/usr/bin/env pwsh
# File header specifies pwsh interpreter location for Linux and MacOS

# Text File User Prompts PowerShell Script

# Use cmdlet to prompt user to enter a string.
# Pipeline operator used to send Read-Host output to Trim method
$strVar = Read-Host "Please enter the file text content"
$filePathVar = Read-Host "Please enter the file path"

# Call the pwsh script to pass the 2 string variables
#Invoke-Expression -Command ".\2-strings-to-text-file.ps1" -p1UserString $strVar -p2FilePath $filePathVar
& ".\2-strings-to-text-file.ps1" -p1UserString $strVar -p2FilePath $filePathVar

# SIG # Begin signature block
# ...
# SIG # End signature block
