#!/usr/bin/env pwsh
# File header specifies pwsh interpreter location for Linux and MacOS

# Use cmdlet to prompt user to enter a string.
# Pipeline operator used to send Read-Host output to Trim method
$stringVariable = Read-Host "Please enter the file text content:" | Trim
$filePathVariable = Read-Host "Please enter the file path:" | Trim

# Call the pwsh script to pass the 2 string variables
Invoke-Expression -Command ".\2-string-to-text-file.ps1" -p1
